// This file is autogenerated. Changes will be overwritten.
#include <EWIEGA46WW/moc_bishop.cpp>
#include <EWIEGA46WW/moc_frame.cpp>
#include <EWIEGA46WW/moc_king.cpp>
#include <EWIEGA46WW/moc_knight.cpp>
#include <EWIEGA46WW/moc_mainwindow.cpp>
#include <EWIEGA46WW/moc_pawn.cpp>
#include <EWIEGA46WW/moc_piece.cpp>
#include <EWIEGA46WW/moc_queen.cpp>
#include <EWIEGA46WW/moc_rook.cpp>
#include <EWIEGA46WW/moc_square.cpp>
